import useSWR from "swr"
import Head from "next/head"
import { AiOutlineArrowLeft, AiOutlineArrowRight } from "react-icons/ai"

import Layout from "@/components/Layout"
import Product from "@/components/Product"
import { product } from "@/types/type"
import { useState } from "react"

const fetcher = (...args: any) => fetch(args).then((res) => res.json())

export default function Home() {
  const { data, error, isLoading } = useSWR<Array<product>>(
    "https://fakestoreapi.com/products",
    fetcher
  )

  const [currentpage, setCurrentPage] = useState<number>(0)

  if (data) {
    console.log(data)
  }
  return (
    <>
      <Head>
        <title>ShopApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        {isLoading && (
          <div className="text-5xl text-center font-extrabold mx-auto my-16 h-screen">
            Your shop is <span className="text-main">Loading</span>
          </div>
        )}

        {data && (
          <div className="flex flex-col mt-10">
            {data
              .filter(
                (x) => x.id > currentpage * 5 && x.id < currentpage * 5 + 6
              )
              .map((x) => (
                <Product product={x} />
              ))}

            <div className="flex justify-around text-3xl mt-10 font-extrabold">
              <div onClick={() => setCurrentPage(currentpage - 1)}>
                {currentpage != 0 && <AiOutlineArrowLeft />}
              </div>
              <div className="flex">
                <div
                  onClick={() => setCurrentPage(0)}
                  className={
                    currentpage == 0
                      ? "text-main underline w-10 h-10 text-center"
                      : " w-10 h-10 text-center"
                  }
                >
                  1
                </div>
                <div
                  onClick={() => setCurrentPage(1)}
                  className={
                    currentpage == 1
                      ? "text-main underline w-10 h-10 text-center"
                      : " w-10 h-10 text-center"
                  }
                >
                  2
                </div>
                <div
                  onClick={() => setCurrentPage(2)}
                  className={
                    currentpage == 2
                      ? "text-main underline w-10 h-10 text-center"
                      : " w-10 h-10 text-center"
                  }
                >
                  3
                </div>
                <div
                  onClick={() => setCurrentPage(3)}
                  className={
                    currentpage == 3
                      ? "text-main underline w-10 h-10 text-center"
                      : " w-10 h-10 text-center"
                  }
                >
                  4
                </div>
              </div>
              <div onClick={() => setCurrentPage(currentpage + 1)}>
                {currentpage != 3 && <AiOutlineArrowRight />}
              </div>
            </div>
          </div>
        )}
      </Layout>
    </>
  )
}
