import useSWR from "swr"
import Head from "next/head"

import Layout from "@/components/Layout"
import Product from "@/components/Product"
import { product } from "@/types/type"
import CartContext from "@/contexts/CartContext"

const fetcher = (...args: any) => fetch(args).then((res) => res.json())

export default function Home() {
  const { data, error, isLoading } = useSWR<Array<product>>(
    "https://fakestoreapi.com/products?limit=10",
    fetcher
  )

  if (data) {
    console.log(data)
  }
  return (
    <>
      <Head>
        <title>ShopApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <CartContext>
        <Layout>
          {isLoading && (
            <div className="text-3xl text-center font-extrabold mx-auto my-16">
              Your shop is <span className="text-cyan-700">Loading</span>
            </div>
          )}
          {data && (
            <div className="flex flex-col">
              {data.map((x) => (
                <Product product={x} />
              ))}
            </div>
          )}
        </Layout>
      </CartContext>
    </>
  )
}
